### ISSUE TITLE
nimble install questionable fails under nim 1.6.4 Windows

### ISSUE THREAD

**Issue by AlectronikForge** [codex-storage/questionable#34]
Output as follows:

`❯ nimble install questionable
Downloading https://github.com/markspanbroek/questionable using git
       Tip: 2 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in C:\Users\alect\AppData\Local\Temp\nimble_16776\githubcom_markspanbroekqu
estionable\questionable.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     C:\Users\alect\AppData\Local\Temp\nimble_16776\githubcom_markspanbroekquestionable\config.nims(1, 2) Err
or: 'off', 'hint' or 'error' expected, but 'usages' found
        ... printPkgInfo() failed.`

Removing the specified flag works but as I'm still a newbie to nim, I don't know if there's a better solution.

**Comment by markspanbroek** [comment]
Thanks for reporting! I have fixed this in #35. We were using the `--stylecheck:usages` option that wasn't introduced until Nim 1.6.6. The command `nimble install questionable` should work on your machine now, but I would recommend updating your Nim to the latest 1.6.14, if possible.
