### ISSUE TITLE
[Feature] add `.!`

### ISSUE THREAD

**Issue by hamidb80** [codex-storage/questionable#44]
like `!` operator when you confident about the presence of the value:
```nim
let s = some "Hello"
echo s.!len
```

**Comment by markspanbroek** [comment]
Thanks for the suggestion @hamidb80! I'm not sure whether the `.!` would be useful for most cases. You can already use `(!s).len`, and chaining it like you would with `.?` (`a.?b.?c`) is not necessary, because you already remove the optional at the first step.
