### ISSUE TITLE
`errorVariable` and thread safety

### ISSUE THREAD

**Issue by elcritch** [codex-storage/questionable#45]
While digging into https://github.com/codex-storage/questionable/issues/41 I noticed that `binderror` uses a global to store the last error state:

https://github.com/codex-storage/questionable/blob/e56cf86c4a089c78a1b7c3005f13343bfbbe3b48/questionable/private/binderror.nim#L4C10-L4C10

It should probably be made into `var errorVariable: ptr ref CatchableError`.

If it's not a threadvar issues might arise when used with multiple threads. I haven't worked through the precise logic, but some sequence similar to:

- thread1 and thread1 both encounter errors in a `without` clause
- thread1 uses `errorVariable` to store an error ptr
- thread1 is paused and thread2 runs
- thread2 stores its error in `errorVariable`
- thread2 is paused
- thread1 now reads `errorVariable` and gets the error meant for thread2

Probably not all too likely and shouldn't cause a false error case, just report the *wrong* error. That'd still be annoying.

**Comment by markspanbroek** [comment]
Good find, thanks! I was able to reproduce this in a test and adding `{.threadvar.}` indeed fixes the problem: #46
