### ISSUE TITLE
`?` operator doesn't work with `{.async.}` pragma

### ISSUE THREAD

**Issue by tbekas** [codex-storage/questionable#47]
It would be nice to make this syntax work:
```nim
proc computeValue(): Type {.async.} =
  let
    a = ? await service.getSomeValueAsync()
    b = ? await service.getAnotherValueAsync()
    c = ? someComputation(a, b)
  return c

## where proc signatures are
proc getSomeValueAsync(self: Service): Future[?!SomeType]

proc getAnotherValueAsync(self: Service): Future[?!AnotherType]

proc someComputation(a: SomeType, b: AnotherType): ?!Outcome
```

Currently we have to use `without` which is more verbose

```nim
proc computeValue(): Type  {.async.} =

  without a =? await service.getSomeValueAsync(), err:
    return failure(err)

  without b =? await service.getAnotherValueAsync(), err:
    return failure(err)

  without c =? someComputation(a, b), err:
    return failure(err)

  return c
```

**Comment by markspanbroek** [comment]
That would be very nice indeed. The early return `?` operator on results is from https://github.com/arnetheduck/nim-results.

There have been some discussions about this problem before:
https://github.com/status-im/nim-stew/issues/37
https://github.com/status-im/nim-chronos/issues/217

No solution yet, as far as I can tell.

**Comment by tbekas** [comment]
Thanks for the info, I'll close this issue then since it's a duplicate and it's an operator from a different project.
